# This Makefile automaticly generated by /home/jason/head/sip/tfm/contrib/Netxx-0.3.2/tools/mkmf
# File created on: Wed Jul 20 10:06:52 2005
# DO NOT EDIT THIS FILE!


all:
	@(cd src; ${MAKE})

clean: 
	@(cd src; ${MAKE} clean)

realclean:
	@(cd src; ${MAKE} realclean)
	rm -f Makefile

test:
	@(cd src; ${MAKE} test)

install: all
	mkdir -p /usr/local/bin
	mkdir -p /usr/local/include
	mkdir -p /usr/local/lib
	cp Netxx-config /usr/local/bin/Netxx-config
	chmod 755 /usr/local/bin/Netxx-config
	mkdir -p /usr/local/include/Netxx
	cp -r /home/jason/head/sip/tfm/contrib/Netxx-0.3.2/include/Netxx/* /usr/local/include/Netxx
	find /usr/local/include/Netxx -type d | xargs chmod 755
	find /usr/local/include/Netxx -type f | xargs chmod 644
	cp /home/jason/head/sip/tfm/contrib/Netxx-0.3.2/src/libNetxx.a /usr/local/lib/libNetxx.a
	chmod 755 /usr/local/lib/libNetxx.a
	cp /home/jason/head/sip/tfm/contrib/Netxx-0.3.2/src/libNetxx.so /usr/local/lib/libNetxx.so.1
	chmod 755 /usr/local/lib/libNetxx.so.1
	rm -f /usr/local/lib/libNetxx.so
	(cd /usr/local/lib; ln -s libNetxx.so.1 libNetxx.so)

