CBUILD = ../../build

include $(CBUILD)/Makefile.pre

PACKAGES += 	TFM REPRO DUM RESIP RUTIL TFMLIBS OPENSSL ARES DB4CXX PTHREAD POPT NATNAV TFCOMMON REFSUB TURN
TESTPROGRAMS = 	TestLamba.cxx  dumTests.cxx

SRC =  DumUserAgent.cxx \
	DumUaAction.cxx \
	DumEvent.cxx \
	DumExpect.cxx \
	DumFixture.cxx \
	TestClientSubscription.cxx \
	TestServerSubscription.cxx \
	TestClientRegistration.cxx \
	TestUsage.cxx \
	TestInviteSession.cxx \
	TestClientPublication.cxx \
	TestServerOutOfDialogReq.cxx \
	TestClientPagerMessage.cxx \
	TestServerPagerMessage.cxx \
	TfdTcpTransport.cxx \
	TfdTestSipEndPoint.cxx

include $(CBUILD)/Makefile.post


