# $Id: Makefile,v 1.144 2004/05/18 01:40:48 jason Exp $

BUILD = ../build
include $(BUILD)/Makefile.pre

PACKAGES += RESIPROCATE PTHREAD OPENSSL

TARGET_LIBRARY = librutil
TESTPROGRAMS =

SRC = \
	AbstractFifo.cxx \
	BaseException.cxx \
	Coders.cxx \
	Condition.cxx \
	CountStream.cxx \
	Data.cxx \
	DataStream.cxx \
	DnsUtil.cxx \
	FileSystem.cxx \
	HeapInstanceCounter.cxx \
	Lock.cxx \
	Log.cxx \
	Logger.cxx \
	MD5Stream.cxx \
	Mutex.cxx \
	Poll.cxx \
	RecursiveMutex.cxx \
	ParseBuffer.cxx \
	RWMutex.cxx \
	Random.cxx \
	SelectInterruptor.cxx \
	SHA1Stream.cxx \
	Socket.cxx \
	Subsystem.cxx \
	SysLogBuf.cxx \
	SysLogStream.cxx \
	ThreadIf.cxx \
	Timer.cxx \
	Tuple.cxx \
	vmd5.cxx \

include $(BUILD)/Makefile.post
