# This makefile can be called by VS.NET 2003 nmake, after all of the resiprocate libraries have already been compiled via the GUI

CFLAGS=/Od /I "../../" /I "../../../" /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "USE_ARES" /D "_MBCS" /Gm /EHsc /RTC1 /MDd /GS /GR /W3 /c /Wp64 /Zi /TP
RESIPLIBS=..\Debug\rutil.lib 
LFLAGS=/INCREMENTAL /NOLOGO /DEBUG /SUBSYSTEM:CONSOLE /MACHINE:X86 Ws2_32.lib Iphlpapi.lib Dnsapi.lib  kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib $(RESIPLIBS)

all: \
	testCoders.obj testCoders.exe \
	testCountStream.obj testCountStream.exe \
	testData.obj testData.exe \
	testDataPerformance.obj testDataPerformance.exe \
	testDataStream.obj testDataStream.exe \
	testDnsUtil.obj testDnsUtil.exe \
 	testFifo.obj testFifo.exe \
 	testFileSystem.obj testFileSystem.exe \
	testInserter.obj testInserter.exe \
	testIntrusiveList.obj testIntrusiveList.exe \
	testLogger.obj testLogger.exe \
	testMD5Stream.obj testMD5Stream.exe \
	testRandomHex.obj testRandomHex.exe \
	testSelectInterruptor.obj testSelectInterruptor.exe \
	testSHA1Stream.obj testSHA1Stream.exe \
	testSharedPtr.obj testSharedPtr.exe \
	testThreadIf.obj testThreadIf.exe \
	run


.cxx.obj:
	cl $(CFLAGS) $<

.obj.exe:
	link /out:$@ $< $(LFLAGS)	

run: 
	testCoders.exe
	testCountStream.exe
	testData.exe 
	testDataPerformance.exe 
	testDataStream.exe 
        testDnsUtil.exe
	testFifo.exe
	testFileSystem.exe
	testInserter.exe
	testIntrusiveList.exe
#	testLogger.exe    - Win32 log threading is not implemented
	testMD5Stream.exe
	testRandomHex.exe
	testSelectInterruptor.exe
	testSHA1Stream.exe
	testSharedPtr.exe
	testThreadIf.exe

clean:
	@del *.exe
        @del *.obj
	@del *.ilk
