PLATFORM=linux
NRAPPKIT_SRCDIR=../../../../nrappkit/
NRAPPKIT_BUILD_DIR=$(NRAPPKIT_SRCDIR)src/make/linux-fedora

OPENSSL_SRC_DIR=../../../../openssl-0.9.8g/

CC=gcc -g
GLOBAL_CFLAGS += -DLINUX -DLINUX_FEDORA

include ../generic/pre.mk

include ../generic/targets.mk

