# $Id: Makefile,v 1.144 2004/05/18 01:40:48 jason Exp $

BUILD = ../../../../main/build
include $(BUILD)/Makefile.pre

PACKAGES += OPENSSL

CODE_SUBDIRS = 
TARGET_LIBRARY = libresip
TESTPROGRAMS = testDtlsWrapper

SRC = DtlsTimer.cxx \
	DtlsSocket.cxx \
	DtlsFactory.cxx

include $(BUILD)/Makefile.post

