/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-set.m2c
 */
#ifndef APPLTABLE_DATA_SET_H
#define APPLTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */


#ifdef __cplusplus
}
#endif
#endif                          /* APPLTABLE_DATA_SET_H */
