BUILD = ../build
include $(BUILD)/Makefile.pre

PACKAGES += RESIPROCATE RDNS RUTIL OPENSSL PTHREAD ARES

SRC = StatelessProxy.cxx 
TARGET_LIBRARY = libstateless
TESTPROGRAMS =	stateless-proxy.cxx 


include $(BUILD)/Makefile.post
