# $Id: Makefile,v 1.2 2005/04/15 20:23:51 jason Exp $

BUILD = ../../../build

include $(BUILD)/Makefile.pre

TARGET_LIBRARY = libloki

SRC = Singleton.cxx SmallObj.cxx

include $(BUILD)/Makefile.post
