# $Id: Makefile,v 1.9 2004/05/10 01:12:46 jason Exp $

BUILD = ../build
include $(BUILD)/Makefile.pre

PACKAGES += RESIPROCATE OPENSSL ARES PTHREAD

TARGET_LIBRARY = libdum

TESTPROGRAMS = 

SRC =   \
	Repro.cxx \
	RequestContext.cxx \
	ResponseContext.cxx 

include $(BUILD)/Makefile.post
