# $Id: Makefile,v 1.70 2006/02/02 11:09 bcampen Exp $

BUILD = ../../build
CONTRIB = ../../contrib

include $(BUILD)/Makefile.pre

PACKAGES += REPRO RESIP RUTIL ARES OPENSSL PTHREAD POPT


TESTPROGRAMS += testDispatcher.cxx

include $(BUILD)/Makefile.post
