/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RESIPROCATE_H
#define RESIPROCATE_H

/* function declarations */
void init_reSIProcate(void);
Netsnmp_Node_Handler handle_registrationsConfigured;
Netsnmp_Node_Handler handle_registrationsFailed;

#endif /* RESIPROCATE_H */
