"    </main>\n"
"    <footer>\n"
"      <span>REPRO SIP PROXY</span>\n"
"      <a href=\"https://github.com/resiprocate/resiprocate/wiki/About-Repro\"\n"
"         target=\"_blank\" rel=\"noopener noreferrer\">www.resiprocate.org</a>\n"
"    </footer>\n"
"    <script>\n"
"      // Highlight the menu entry for the page currently being viewed.\n"
"      (function () {\n"
"        var page = location.pathname.split('/').pop() || 'index.html';\n"
"        var links = document.querySelectorAll('nav.menu a');\n"
"        for (var i = 0; i < links.length; i++) {\n"
"          if (links[i].getAttribute('href') === page) { links[i].className = 'on'; }\n"
"        }\n"
"      })();\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
