"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"    <title>Repro Proxy</title>\n"
"    <link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='7' fill='%2312294d'/><g stroke='%23ff8d09' stroke-width='2.4' fill='none' stroke-linecap='round'><path d='M8 16h7'/><path d='M15 16l8-6.5'/><path d='M15 16l8 6.5'/></g><circle cx='8' cy='16' r='3' fill='%23ff8d09'/><circle cx='23' cy='9.5' r='3' fill='%23ffb454'/><circle cx='23' cy='22.5' r='3' fill='%23ffb454'/></svg>\" />\n"
"    <style>\n"
"  :root {\n"
"    --bg:        #0a0c0f;\n"
"    --bg2:       #10141a;\n"
"    --bg3:       #161c24;\n"
"    --border:    #1e2730;\n"
"    --green:     #00e676;\n"
"    --green-dim: #00873f;\n"
"    --amber:     #ffab00;\n"
"    --red:       #ff1744;\n"
"    --blue:      #40c4ff;\n"
"    --purple:    #e040fb;\n"
"    --text:      #c8d0da;\n"
"    --text-dim:  #4a5568;\n"
"    --text-mid:  #7a8899;\n"
"    --mono:      'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;\n"
"    /* product mark */\n"
"    --mark-navy: #12294d;\n"
"    --mark-edge: #2f5da8;\n"
"    --mark-amber:#ff8d09;\n"
"    color-scheme: dark;\n"
"  }\n"
"  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"  body {\n"
"    background: var(--bg); color: var(--text);\n"
"    font-family: var(--mono); font-size: 13px; line-height: 1.5;\n"
"    min-height: 100vh;\n"
"    display: grid;\n"
"    grid-template-rows: auto 1fr auto;\n"
"    grid-template-columns: 205px 1fr;\n"
"    grid-template-areas: \"header header\" \"menu main\" \"footer footer\";\n"
"  }\n"
"\n"
"  /* header */\n"
"  header { grid-area: header; display: flex; align-items: center; gap: 14px;\n"
"    padding: 10px 18px; background: var(--bg2); border-bottom: 1px solid var(--border); }\n"
"  .logo { width: 28px; height: 28px; flex-shrink: 0; display: block; }\n"
"  .logo-link { display: flex; flex-shrink: 0; border-radius: 7px; transition: opacity .15s; }\n"
"  .logo-link:hover { opacity: .75; }\n"
"  .logo-link:focus-visible { outline: 1px solid var(--green); outline-offset: 3px; }\n"
"  header h1 { font-size: 12px; font-weight: 600; letter-spacing: .1em; text-transform: uppercase; }\n"
"  header sub { font-size: 10px; color: var(--text-dim); letter-spacing: .06em; }\n"
"  .pills { margin-left: auto; display: flex; gap: 8px; }\n"
"  .status-pill { display: flex; align-items: center; gap: 7px; padding: 4px 10px;\n"
"    border: 1px solid var(--border); border-radius: 2px;\n"
"    font-size: 11px; color: var(--text-mid); letter-spacing: .06em; }\n"
"  .dot { width: 7px; height: 7px; border-radius: 50%; background: var(--green);\n"
"    box-shadow: 0 0 6px var(--green); }\n"
"\n"
"  /* side menu */\n"
"  nav.menu { grid-area: menu; background: var(--bg2); border-right: 1px solid var(--border);\n"
"    padding: 14px 0 20px; overflow: hidden; }\n"
"  nav.menu .grp { margin-bottom: 14px; }\n"
"  nav.menu .grp-lbl { font-size: 10px; letter-spacing: .14em; text-transform: uppercase;\n"
"    color: var(--text-dim); padding: 0 14px; margin-bottom: 5px; }\n"
"  nav.menu a { display: block; padding: 4px 14px; font-size: 12px; text-decoration: none;\n"
"    white-space: nowrap; color: var(--text-mid); border-left: 2px solid transparent;\n"
"    transition: all .12s; }\n"
"  nav.menu a:hover { color: var(--text); background: var(--bg3); border-left-color: var(--text-dim); }\n"
"  nav.menu a.on { color: var(--green); border-left-color: var(--green); background: rgba(0,230,118,.06); }\n"
"\n"
"  /* main */\n"
"  main.main { grid-area: main; min-width: 0; padding: 18px 20px 26px; overflow-x: auto; }\n"
"  h1 { font-size: 17px; font-weight: 600; letter-spacing: .04em; margin-bottom: 12px; }\n"
"  h2 { font-size: 11px; font-weight: 600; letter-spacing: .14em; text-transform: uppercase;\n"
"    color: var(--green); margin: 0 0 12px; padding-bottom: 6px; border-bottom: 1px solid var(--border); }\n"
"  main.main h2 ~ h2 { margin-top: 26px; }\n"
"  h3 { font-size: 12px; font-weight: 600; margin: 18px 0 8px; color: var(--text); }\n"
"  h4 { font-size: 11px; font-weight: 400; font-style: oblique; margin: 12px 0 6px; color: var(--text-mid); }\n"
"  p { margin: 0 0 10px; color: var(--text-mid); max-width: 78ch; }\n"
"  p.hint { font-size: 11px; color: var(--text-dim); margin: 2px 0 14px; }\n"
"  a { color: var(--blue); text-decoration: none; }\n"
"  a:hover { text-decoration: underline; }\n"
"  hr { border: 0; border-top: 1px solid var(--border); margin: 14px 0; }\n"
"  .space { height: 10px; font-size: 5px; }\n"
"  em { font-style: normal; font-weight: 600; color: var(--text); }\n"
"  em.warn { color: var(--amber); }\n"
"  em.ok { color: var(--green); }\n"
"\n"
"  /* status notices emitted by the sub pages */\n"
"  .notice { display: inline-block; border: 1px solid var(--border); border-left-width: 2px;\n"
"    border-radius: 2px; background: var(--bg2); padding: 7px 11px; margin: 0 0 12px;\n"
"    color: var(--text); max-width: 100%; }\n"
"  .notice em { letter-spacing: .06em; }\n"
"  .notice.ok   { border-left-color: var(--green); }\n"
"  .notice.ok em   { color: var(--green); }\n"
"  .notice.err  { border-left-color: var(--red); }\n"
"  .notice.err em  { color: var(--red); }\n"
"  .notice.warn { border-left-color: var(--amber); }\n"
"  .notice.warn em { color: var(--amber); }\n"
"\n"
"  /* tables: form-table is the borderless label/field layout,\n"
"     data-table is the bordered record listing */\n"
"  table { border-collapse: collapse; }\n"
"  .form-table { margin-bottom: 4px; }\n"
"  .form-table td { padding: 3px 6px 3px 0; vertical-align: middle; color: var(--text-mid); }\n"
"  .form-table td[align=\"right\"] { font-size: 10px; letter-spacing: .08em;\n"
"    text-transform: uppercase; color: var(--text-mid); white-space: nowrap; }\n"
"\n"
"  /* Sized to its contents rather than stretched to the viewport.  Deliberately no\n"
"     max-width: a wide table (registrations) should scroll inside main rather than\n"
"     squeeze its columns down to one character per line. */\n"
"  .data-table { width: auto; background: var(--bg2);\n"
"    border: 1px solid var(--border); border-radius: 2px; margin-bottom: 4px; }\n"
"  .data-table thead td { font-size: 10px; letter-spacing: .1em; text-transform: uppercase;\n"
"    color: var(--text-dim); background: var(--bg3); padding: 6px 9px; text-align: left;\n"
"    border-bottom: 1px solid var(--border); white-space: nowrap; }\n"
"  .data-table tbody td { padding: 5px 9px; border-bottom: 1px solid rgba(30,39,48,.6);\n"
"    vertical-align: top; white-space: nowrap; }\n"
"  .data-table tbody tr:last-child td { border-bottom: 0; }\n"
"  .data-table tbody tr:hover { background: rgba(64,196,255,.04); }\n"
"\n"
"  /* form controls */\n"
"  input[type=\"text\"], input[type=\"password\"], select, textarea {\n"
"    background: var(--bg3); border: 1px solid var(--border); border-radius: 2px;\n"
"    color: var(--text); font-family: var(--mono); font-size: 12px;\n"
"    padding: 4px 7px; outline: none; transition: border-color .15s; }\n"
"  input[type=\"text\"]:focus, input[type=\"password\"]:focus, select:focus {\n"
"    border-color: var(--green-dim); }\n"
"  ::placeholder { color: var(--text-dim); opacity: 1; }\n"
"  select option { background: var(--bg3); color: var(--text); }\n"
"  /* the browser default checkbox is a white block that glares on a dark page */\n"
"  input[type=\"checkbox\"] { appearance: none; -webkit-appearance: none; position: relative;\n"
"    width: 14px; height: 14px; vertical-align: middle; cursor: pointer;\n"
"    background: var(--bg3); border: 1px solid var(--border); border-radius: 2px;\n"
"    transition: all .12s; }\n"
"  input[type=\"checkbox\"]:hover { border-color: var(--text-mid); }\n"
"  input[type=\"checkbox\"]:checked { background: var(--green); border-color: var(--green); }\n"
"  input[type=\"checkbox\"]:checked::after { content: ''; position: absolute;\n"
"    left: 4px; top: 1px; width: 3px; height: 7px; border: solid var(--bg);\n"
"    border-width: 0 2px 2px 0; transform: rotate(45deg); }\n"
"\n"
"  input[type=\"submit\"], input[type=\"reset\"], button {\n"
"    background: transparent; border: 1px solid var(--border); border-radius: 2px;\n"
"    color: var(--text-mid); font-family: var(--mono); font-size: 10px; font-weight: 600;\n"
"    letter-spacing: .1em; text-transform: uppercase; padding: 5px 12px;\n"
"    cursor: pointer; transition: all .15s; }\n"
"  input[type=\"submit\"] { border-color: var(--green-dim); color: var(--green); }\n"
"  input[type=\"submit\"]:hover { background: var(--green); color: var(--bg); border-color: var(--green); }\n"
"  input[type=\"reset\"]:hover, button:hover { border-color: var(--text-mid); color: var(--text); }\n"
"  input[type=\"submit\"][value=\"Remove\"] { border-color: var(--red); color: var(--red); }\n"
"  input[type=\"submit\"][value=\"Remove\"]:hover { background: var(--red); color: var(--bg); }\n"
"  input[type=\"submit\"][value=\"Restart Proxy\"] { border-color: var(--amber); color: var(--amber); }\n"
"  input[type=\"submit\"][value=\"Restart Proxy\"]:hover { background: var(--amber); color: var(--bg); }\n"
"\n"
"  /* a row of action forms/buttons that should sit side by side */\n"
"  .toolbar { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin-bottom: 14px; }\n"
"  .toolbar form { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }\n"
"  .toolbar label { font-size: 10px; letter-spacing: .1em; text-transform: uppercase;\n"
"    color: var(--text-mid); }\n"
"\n"
"  /* Server dumps (settings, stack info, DNS cache).  Deliberately no max-height:\n"
"     these grow to fit so the page scrolls instead of nesting a scrollbar. */\n"
"  pre { background: var(--bg2); border: 1px solid var(--border); border-radius: 2px;\n"
"    padding: 9px 11px; margin: 0 0 12px; font-family: var(--mono); font-size: 11.5px;\n"
"    line-height: 1.6; color: var(--text-mid); overflow-x: auto; }\n"
"\n"
"  /* Explanatory copy that introduces a page.  Sits above the form it describes,\n"
"     and is plain text -- no panel, so it does not read as page content. */\n"
"  .help { margin: 0 0 18px; max-width: 96ch; color: var(--text-mid); }\n"
"  .help p { margin: 0 0 8px; max-width: none; }\n"
"  .help p:last-child { margin-bottom: 0; }\n"
"  .help pre { background: none; border: 0; border-radius: 0; padding: 0;\n"
"    margin: 0 0 8px; color: var(--text-dim); }\n"
"\n"
"  /* footer */\n"
"  footer { grid-area: footer; display: flex; align-items: center; gap: 18px;\n"
"    padding: 7px 18px; background: var(--bg2); border-top: 1px solid var(--border);\n"
"    font-size: 10px; letter-spacing: .06em; color: var(--text-dim); }\n"
"\n"
"  @media (max-width: 720px) {\n"
"    body { grid-template-columns: 1fr; grid-template-areas: \"header\" \"menu\" \"main\" \"footer\"; }\n"
"    nav.menu { border-right: 0; border-bottom: 1px solid var(--border); }\n"
"    header sub { display: none; }\n"
"  }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"\n"
"    <header>\n"
"      <!-- product mark: a request arriving at the proxy and being forked onward -->\n"
"      <a class=\"logo-link\" href=\"https://github.com/resiprocate/resiprocate/wiki/About-Repro\"\n"
"         target=\"_blank\" rel=\"noopener noreferrer\" title=\"About Repro\">\n"
"        <svg class=\"logo\" viewBox=\"0 0 32 32\" role=\"img\" aria-label=\"About Repro\">\n"
"          <rect x=\"0.9\" y=\"0.9\" width=\"30.2\" height=\"30.2\" rx=\"6.5\"\n"
"                fill=\"var(--mark-navy)\" stroke=\"var(--mark-edge)\" stroke-width=\"1.6\" />\n"
"          <g stroke=\"var(--mark-amber)\" stroke-width=\"2.2\" fill=\"none\" stroke-linecap=\"round\">\n"
"            <path d=\"M8 16h7\" />\n"
"            <path d=\"M15 16l8-6.5\" />\n"
"            <path d=\"M15 16l8 6.5\" />\n"
"          </g>\n"
"          <circle cx=\"8\" cy=\"16\" r=\"3\" fill=\"var(--mark-amber)\" />\n"
"          <circle cx=\"23\" cy=\"9.5\" r=\"3\" fill=\"#ffb454\" />\n"
"          <circle cx=\"23\" cy=\"22.5\" r=\"3\" fill=\"#ffb454\" />\n"
"        </svg>\n"
"      </a>\n"
"      <h1>Repro</h1>\n"
"      <sub>SIP PROXY &middot; ADMIN CONSOLE</sub>\n"
"      <div class=\"pills\">\n"
"        <div class=\"status-pill\"><span class=\"dot\"></span><span>vVERSION</span></div>\n"
"      </div>\n"
"    </header>\n"
"\n"
"    <nav class=\"menu\">\n"
"      <div class=\"grp\">\n"
"        <div class=\"grp-lbl\">Base Configuration</div>\n"
"        <a href=\"domains.html\">Domains</a>\n"
"        <a href=\"acls.html\">ACLs</a>\n"
"      </div>\n"
"      <div class=\"grp\">\n"
"        <div class=\"grp-lbl\">Users</div>\n"
"        <a href=\"addUser.html\">Add User</a>\n"
"        <a href=\"showUsers.html\">Show Users</a>\n"
"      </div>\n"
"      <div class=\"grp\">\n"
"        <div class=\"grp-lbl\">Request Filters</div>\n"
"        <a href=\"addFilter.html\">Add Filter</a>\n"
"        <a href=\"showFilters.html\">Show Filters</a>\n"
"      </div>\n"
"      <div class=\"grp\">\n"
"        <div class=\"grp-lbl\">Routes</div>\n"
"        <a href=\"addRoute.html\">Add Route</a>\n"
"        <a href=\"showRoutes.html\">Show Routes</a>\n"
"      </div>\n"
"      <div class=\"grp\">\n"
"        <div class=\"grp-lbl\">Live Info</div>\n"
"        <a href=\"registrations.html\">Registrations</a>\n"
"        <a href=\"publications.html\">Publications</a>\n"
"        <a href=\"settings.html\">Stack Info &amp; Settings</a>\n"
"      </div>\n"
"    </nav>\n"
"\n"
"    <main class=\"main\">\n"
